version: "3"

services:
  client:
    build: ./client
    stdin_open: true
    tty: true
    command: npm run dev
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
volumes:
  mysql_data:
